# Day 01 Part 1

In [ ]:
freq = 0
with open("day01.txt", "r") as file:
    for line in file:
        if line[0] == "+":
            freq += int(line[1:-1])
        else:
            freq -= int(line[1:-1])
print(freq)

# Day 01 Part 2

In [ ]:
freq = 0
checklist = set()
checklist.add(freq)
found = False
while(not found):
    with open("day01.txt", "r") as file:
        for line in file:
            if line[0] == "+":
                freq += int(line[1:-1])
            else:
                freq -= int(line[1:-1])
            if freq in checklist:
                found = True
                print(freq)
                break
            else:
                checklist.add(freq)
    

# Day 02 Part 1

In [ ]:
countOf2 = 0
countOf3 = 0

with open("day02.txt", "r") as file:
    for line in file:
        
        counts= {}
        for letter in line:
            if letter in counts:
                counts[letter] += 1
            else:
                counts[letter] = 1
        if 2 in counts.values():
            countOf2 += 1
        if 3 in counts.values():
            countOf3 += 1
            
print(countOf2 * countOf3)

# Day 02 Part 2

In [ ]:
checklist = list()
with open("day02.txt", "r") as file:
    for line in file:
        for i, letter in enumerate(line):
            if i == len(checklist):
                checklist.append(set())
            str = line[0:i] + line[i+1::]
            if str in checklist[i]:
                print(str)
                break 
            else:
                checklist[i].add(str)
            

# Day 03 Part 1

In [ ]:
import re

checkerboard = [[0 for i in range(2000)] for i in range(2000)]
pattern = re.compile("#(\d+) @ (\d+),(\d+): (\d+)x(\d+)\n")
with open("day03.txt", "r") as file:
    for line in file:
        m = pattern.match(line)
        if m:
            id = m.group(1)
            x = int(m.group(2))
            y = int(m.group(3))
            width = int(m.group(4))
            length = int(m.group(5))
            
            for i in range(width):
                for j in range(length):
                    checkerboard[x+i][y+j] += 1
print(sum([sum([1 if val > 1 else 0 for val in row]) for row in checkerboard]))

# Day 03 Part 2

In [ ]:
import re

checkerboard = [[0 for i in range(2000)] for i in range(2000)]
pattern = re.compile("#(\d+) @ (\d+),(\d+): (\d+)x(\d+)\n")

# Populate the checkerboard first
with open("day03.txt", "r") as file:
    for line in file:
        m = pattern.match(line)
        if m:
            id = m.group(1)
            x = int(m.group(2))
            y = int(m.group(3))
            width = int(m.group(4))
            length = int(m.group(5))
            
            for i in range(width):
                for j in range(length):
                    checkerboard[x+i][y+j] += 1
                    
# Check for overlap
with open("day03.txt", "r") as file:
    for line in file:
        overLap = False
        m = pattern.match(line)
        if m:
            id = m.group(1)
            x = int(m.group(2))
            y = int(m.group(3))
            width = int(m.group(4))
            length = int(m.group(5))
            
            for i in range(width):
                for j in range(length):
                    if checkerboard[x+i][y+j] != 1:
                        overLap = True
                        break
                if overLap:
                    break
            if not overLap:
                print(id)
                break
                        

# Day 04 Part 1

In [ ]:
import re

shiftLogPattern = re.compile("\[1518-\d{2}-\d{2} \d{2}:\d{2}\] Guard #(\d+) begins shift")
wakeLogPattern = re.compile("\[1518-\d{2}-\d{2} \d{2}:(\d{2})\] wakes up")
asleepLogPattern = re.compile("\[1518-\d{2}-\d{2} \d{2}:(\d{2})\] falls asleep")
lines = list()
guardId = None
lastAwake = None

slackers = {}
with open("day04.txt", "r") as file:
    lines = sorted(file)
for line in lines:
    m = shiftLogPattern.match(line)
    if m:
        guardId = m.group(1)
        if guardId not in slackers:
            slackers[guardId] = [0] * 60
        continue
    
    m = asleepLogPattern.match(line)
    if m:
        lastAwake = int(m.group(1)) - 1
        continue
        
    m = wakeLogPattern.match(line)
    if m:
        for i in range(int(m.group(1)) - lastAwake):
            slackers[guardId][lastAwake+1+i] += 1
        continue
        
slackest = None
slackestMinutes = 0

for guardId, timestamps in slackers.items():
    timeSlacking = sum(timestamps)
    if slackestMinutes < timeSlacking:
        slackest = guardId
        slackestMinutes = timeSlacking

print("Slackest Guard: " + slackest)

slackestTimestamp = slackers[slackest].index(max(slackers[slackest]))
print("Slackest Minute: " + str(slackestTimestamp))
print("Answer: " + str(slackestTimestamp * int(slackest)))

# Day 04 Part 2

In [ ]:
slackest = None
slackestMinuteOccurence = 0
slackestMinute = None

for guardId, timestamps in slackers.items():
    occurence = max(timestamps)
    if slackestMinuteOccurence < occurence:
        slackest = guardId
        slackestMinuteOccurence = occurence
        slackestMinute = timestamps.index(occurence)

print("Slackest Guard: " + slackest)
print("SlackestMinute: " + str(slackestMinute))
print("Ans: " + str(slackestMinute * int(slackest)))

# Day 05 Part 1

In [ ]:
def react(polymer):
    polymer = polymer.rstrip()
    counter = 0
    while(counter != len(polymer) - 1):
        if polymer[counter] != polymer[counter+1] and polymer[counter].lower() == polymer[counter+1].lower():
            polymer = polymer[:counter] + (polymer[counter+2:] if len(polymer) > counter + 2 else "")
            if counter != 0:
                counter-=1
        else:
            counter+=1
    return polymer

with open("day05.txt", "r") as input:
    polymer = input.read().rstrip()
    polymer = react(polymer)            
#     print("Polymer: " + polymer)
    print("Ans: " + str(len(polymer)))

# Day 05 Part 2

In [ ]:
import re
import string
import sys

shortestPolymer = sys.maxint
with open("day05.txt", "r") as input:
    polymer = input.read().rstrip()
    for alphabet in string.ascii_lowercase:
        testPolymer = re.sub(alphabet + "|" + alphabet.upper() , "", polymer)
        testPolymer = react(testPolymer)
        if shortestPolymer > len(testPolymer):
            shortestPolymer = len(testPolymer)
print("Ans: " + str(shortestPolymer))

# Day 06 Part 1

In [27]:
import re
import numpy as np
from collections import Counter
import sys

EMPTY_CELL = -1 # Empty Cell Representation

boardSize = 400
currBoard = np.zeros((boardSize, boardSize), dtype=int) + EMPTY_CELL

coords = list()
def manhattanDist(a,b):
    return abs(a[0]-b[0]) + abs(a[1]-b[1])

with open("day06.txt", "r") as input:
    coordinatePattern = re.compile("(\d+), (\d+)")
    
    for i, line in enumerate(input):
        m = coordinatePattern.match(line)
        if m:
            x = int(m.group(1))
            y = int(m.group(2))
            coords.append((x,y))

for x in range(boardSize):
    for y in range(boardSize):
        
        closestCoord = EMPTY_CELL
        closestDist = sys.maxint
        for i, coord in enumerate(coords):
            dist = manhattanDist((x,y), coord)
#             print("dist: " + str(dist))
#             print(closestDist)
#             print("closestCoord: " + str(closestCoord))
            if closestDist > dist:
                closestCoord = i
                closestDist = dist
            elif closestDist == dist:
                closestCoord = EMPTY_CELL
        
        currBoard[x][y] = closestCoord
#         print(currBoard)

print(currBoard)
for i in range(boardSize):
#       Detect areas that are infinite
#       First Col
    if currBoard[i][0] != EMPTY_CELL:
        toReplace = currBoard[i][0]
        currBoard[currBoard==toReplace] = EMPTY_CELL
#       Last Col
    if currBoard[i][boardSize-1] != EMPTY_CELL:
        toReplace = currBoard[i][boardSize-1]
        currBoard[currBoard==toReplace] = EMPTY_CELL
#       First Row
    if currBoard[0][i] != EMPTY_CELL:
        toReplace = currBoard[0][i]
        currBoard[currBoard==toReplace] = EMPTY_CELL
#      Last Row
    if currBoard[boardSize-1][i] != EMPTY_CELL:
        toReplace = currBoard[boardSize-1][i]
        currBoard[currBoard==toReplace] = EMPTY_CELL
    
counter = Counter(currBoard.flatten())

# Show two most common element and number of them
# As there will be a lot of EMPTY_CELL, the answer should be the second most
print("ans: " + str(counter.most_common(2)))

[[12 12 12 ... 20 20 20]
 [12 12 12 ... 20 20 20]
 [12 12 12 ... 20 20 20]
 ...
 [43 43 43 ... 24 24 24]
 [43 43 43 ... 24 24 24]
 [43 43 43 ... 24 24 24]]
ans: [(-1, 108187), (47, 5532)]


In [38]:
import re
import numpy as np
from collections import Counter
import sys
boardSize = 400
bitBoard = np.ones((boardSize, boardSize), dtype=int)
THRESHOLD = 10000
coords = list()
def manhattanDist(a,b):
    return abs(a[0]-b[0]) + abs(a[1]-b[1])

with open("day06.txt", "r") as input:
    coordinatePattern = re.compile("(\d+), (\d+)")
    
    for i, line in enumerate(input):
        m = coordinatePattern.match(line)
        if m:
            x = int(m.group(1))
            y = int(m.group(2))
            coords.append((x,y))

for x in range(boardSize):
    for y in range(boardSize):
        totalDist = 0
        
        for i, coord in enumerate(coords):
            totalDist += manhattanDist((x,y), coord)
#             print("dist: " + str(dist))
        if THRESHOLD <= totalDist:
            bitBoard[x][y] = 0

print(bitBoard)
print("ans: " + str(sum(sum(bitBoard))))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
ans: 36216


# Day 07 Part 1

In [1]:
import re
import heapq

instPattern = re.compile("Step (\w) must be finished before step (\w) can begin.")

insts = set()
precedents = {}

with open("day07.txt", "r") as input:
    
    for line in input:
        m = instPattern.match(line)
        if m:
            precedent = m.group(1)
            ancedent = m.group(2)
                
            insts.add(precedent)
            
            if ancedent not in precedents:
                precedents[ancedent] = set()
                
            precedents[ancedent].add(precedent)

roots = list()
for inst in insts:
    if inst not in precedents:
        roots.append(inst)
        
heapq.heapify(roots)

print("roots: ")
print(roots)

print("precedents: ")
print(precedents)


result = list()
while(len(roots) > 0):
    popped = heapq.heappop(roots)
        
    result.append(popped)
    
    for ancedent, precedentSet in precedents.items():
        if popped in precedentSet:
            precedentSet.remove(popped)
            if len(precedentSet) == 0:
                precedents.pop(ancedent)
                heapq.heappush(roots, ancedent)
        
print()
print("ans: " + "".join(result))
    

roots: 
['I', 'U', 'T', 'W']
precedents: 
{'A': set(['Y', 'K', 'J', 'D']), 'C': set(['P', 'K', 'E', 'M', 'O']), 'B': set(['I']), 'E': set(['I', 'V']), 'D': set(['K', 'T', 'F']), 'G': set(['I', 'W']), 'F': set(['G']), 'H': set(['Y', 'N', 'D', 'W', 'V']), 'K': set(['G']), 'J': set(['I']), 'M': set(['G', 'F', 'K', 'J', 'O', 'U', 'Y']), 'L': set(['P', 'R', 'M', 'G', 'W']), 'O': set(['A', 'B', 'D', 'F', 'N', 'U', 'T', 'W']), 'N': set(['J', 'D', 'W', 'F']), 'Q': set(['I', 'Y', 'U', 'T']), 'P': set(['K', 'D', 'O']), 'S': set(['H', 'K', 'R', 'E', 'L']), 'R': set(['C', 'E', 'I', 'H', 'M', 'O', 'Q', 'P', 'U']), 'V': set(['K', 'N']), 'Y': set(['K', 'T', 'W', 'N']), 'X': set(['A', 'E', 'F', 'K', 'J', 'M', 'L', 'S', 'R', 'U', 'T', 'W', 'V', 'Y', 'Z']), 'Z': set(['A', 'C', 'D', 'F', 'M', 'L', 'Q', 'P', 'S', 'Y'])}

ans: IBJTUWGFKDNVEYAHOMPCQRLSZX


# Day 07 Part 2

In [9]:
import re
import heapq

instPattern = re.compile("Step (\w) must be finished before step (\w) can begin.")

insts = set()
precedents = {}
numWorkers = 5
instsInProgress = {}

with open("day07.txt", "r") as input:
    
    for line in input:
        m = instPattern.match(line)
        if m:
            precedent = m.group(1)
            ancedent = m.group(2)
                
            insts.add(precedent)
            
            if ancedent not in precedents:
                precedents[ancedent] = set()
                
            precedents[ancedent].add(precedent)

roots = list()
for inst in insts:
    if inst not in precedents:
        roots.append(inst)
        
heapq.heapify(roots)
timeTaken = 0
result = list()
while(len(roots) > 0 or len(instsInProgress) > 0):
    while len(instsInProgress) < 5 and len(roots) > 0:
        popped = heapq.heappop(roots)
        result.append(popped)
        instsInProgress[popped] = 61 + (ord(popped) - ord("A"))
        
    for inst in instsInProgress.keys():
        instsInProgress[inst] -= 1
        if instsInProgress[inst] == 0:
            instsInProgress.pop(inst)
            for ancedent, precedentSet in precedents.items():
                if inst in precedentSet:
                    precedentSet.remove(inst)
                    if len(precedentSet) == 0:
                        precedents.pop(ancedent)
                        heapq.heappush(roots, ancedent)
    
    timeTaken += 1    

print("execution: " + "".join(result))
print("ans: " + str(timeTaken))

execution: ITUWBJGFKDNVYEAHQOMPCRLSZX
ans: 1118
